### ISSUE TITLE
Cannot fold multiline function/classes signatures.

### ISSUE THREAD

**Issue by grillermo** [tmhedberg/SimpylFold#1]
Ran into a nasty issue, function signatures with the parameters spanning multiple lines for example i got this:
def activate(request, backend,
             template_name='registration/activate.html',
             success_url=None, extra_context=None, **kwargs):
             block_of_function

Cannot be folded :( i know folding in python is a tricky issue, i'll try other plugins and let you know if any can handle that.

**Comment by varunsaravagi** [comment]
This it still an issue I believe. 
```
def test(
    a,
    b,
    c
):
    print("Hello world")
```

is folded as
```
def test(...
):
    print("Hello world")
```
