### ISSUE TITLE
Cause vim to run slowly

### ISSUE THREAD

**Issue by f7r** [tmhedberg/SimpylFold#102]
After enable this plugin, vim opens long text files slower and CPU usage becomes higher.

**Comment by tmhedberg** [comment]
Can you share an example file that has this problem?

**Comment by tmhedberg** [comment]
I'm not sure I understand whether you're saying that the problem is with this plugin or something unrelated to SimpylFold in your Vim configuration.

**Comment by f7r** [comment]
I used SimpylFold to find that vim is slow, but there seems to be no better solution. The vim documentation says that using foldexpr will be slow, so it may not be a problem with SimpylFold.
