### ISSUE TITLE
Docstring fold breaks syntax highlighting

### ISSUE THREAD

**Issue by lindhe** [tmhedberg/SimpylFold#103]
I find that syntax highlighting is often broken when this plugin folds docstrings. Looks like the rest of the code gets interpreted like comments. Is that a known issue?

I'm on mobile now, but will corroborate further when I get the chance. Just wanted to put this here, or I will forget.

**Comment by tmhedberg** [comment]
I've seen this kind of thing happen with a lot of folding plugins for different languages, actually. I'm not sure it's unique to SimpylFold; it may be an underlying Vim bug. It happens to me pretty frequently when using a Markdown plugin with folds.

If you have a reliably reproducible case, please share it, but I don't know how much we'll be able to do about it.

As a workaround, running `:syntax sync fromstart` usually fixes it for me, at least temporarily.

**Comment by lindhe** [comment]
It's not just an underlying Vim bug, because it works perfectly when I fold manually. But I'll try and see if I can get some minimal broken example in order.

**Comment by lindhe** [comment]
No, it was Vim. I just happened to switch folding less often with manual folds than with your plugin, and therefore didn't notice it as quickly.
