### ISSUE TITLE
weird characters are shown on the first line of the folding

### ISSUE THREAD

**Issue by jdhao** [tmhedberg/SimpylFold#104]
There are some weird characters showing up in the first line of the folding, which depends on the ssh program I use.

On ZOC and Putty, the characters are displayed well:

![image](https://user-images.githubusercontent.com/16662357/45666083-a4b17c00-bb46-11e8-91e7-ffff9eb357a2.png)

But on Mobaxterm, the characters are not displayed correctly:

![image](https://user-images.githubusercontent.com/16662357/45666107-cc084900-bb46-11e8-8b4d-3de3fc54193b.png)

Do you have any idea on how to fix this problem?

**Comment by tmhedberg** [comment]
This is almost certainly not an issue with SimpylFold, but rather a problem with your terminal's character encoding. Vim fills that section of the fold line with a character determined by the value of the `fillchars` option. My guess is that the terminal in your second screenshot is using an different encoding, so whatever byte sequence you have in `fillchars` is being interpreted differently by the second terminal.

Make sure your terminals are configured to use the same encoding and see if that helps.

**Comment by jdhao** [comment]
I have set the encoding for both ssh client to be UTF-8 encoding. Anyway, I reset the fillchars for folding and now the characters shown are normal. 

![image](https://user-images.githubusercontent.com/16662357/45741905-4c07df00-bc2b-11e8-9e33-a8bce4f3ec35.png)

I use the following setting in my Neovim configuration file:

```
set fillchars=fold:-
```
