### ISSUE TITLE
Include trailing lines in folds

### ISSUE THREAD

**Issue by YodaEmbedding** [tmhedberg/SimpylFold#105]
As shown here, the spaces between folds have many negatives:

 - slower navigation (`2j` per fold instead of a single `j`)
 - difficult to scan and find the desired fold quickly
 - difficult to cut/paste folds around (have to deal with extra lines)
 - take twice as much space

![bad folds](https://i.imgur.com/UPkS4OX.png)

In contrast, we have the elegant, compact, usable, aesthetic, and all around awesome proposition:

![good folds](https://i.imgur.com/XYQZUYY.png)

Bonus points if we can get rid of the decorators. (This _might_ be more difficult, though.)

**Could this be made either an option or, more adventurously, the default behavior?**

**Comment by tmhedberg** [comment]
Correct me if I'm mistaken, but this seems to be essentially the same request as in #34 (and #86 for decorator folding). Someone in that thread has a prototype that you could try out, and maybe spur along the completion of that patch if you really want this functionality. I'd accept a pull request for it if it reaches a good state.

> slower navigation (2j per fold instead of a single j)

In case you weren't aware of it, you can also navigate between folds with `zj` and `zk`, so you don't have to use counts with linewise motions even if they're spaced apart.

**Comment by tmhedberg** [comment]
This was added as an option (`g:SimpylFold_fold_blank`) a while back.
