### ISSUE TITLE
How to refresh folds on an already open vim .py file?

### ISSUE THREAD

**Issue by evan54** [tmhedberg/SimpylFold#107]
When I modify a file the folds seems to not "refresh"? Is there a way to manually refresh folds?p

**Comment by iago-lito** [comment]
Try `:e<cr>`, it is often enough for me :)

**Comment by tmhedberg** [comment]
You shouldn't need to do anything to recompute the folds; it should happen automatically unless you have another plugin that's modifying your folding settings. That said, `zx` can be used to force all folds to be recomputed without the side effects of `:edit` (reloading the file from disk).

**Comment by evan54** [comment]
thanks for the answers closing this now

**Comment by pianocomposer321** [comment]
I added this to my .vimrc:
```
au BifWrite * normal zx
```
