### ISSUE TITLE
Missfolding on file having ^M (DOS style) as EOL

### ISSUE THREAD

**Issue by dnyaneshgate** [tmhedberg/SimpylFold#109]
I work with python files having ^M (dos style) as end of line (fileformat is set to unix). This EOL style causes plugin to missfold.
Removing this char, fix the issue, but can not remove these character; because it will modify all lines in file and will also disrupt git diff.

Is there any way, where this plugin can handle "^M" and fold crrectly?

**Comment by tmhedberg** [comment]
Why is `fileformat` set to `unix` if the line endings are not Unix-style? Have you tried setting it to the correct value?

**Comment by tmhedberg** [comment]
A lot of things are bound to break if you have files with mixed line endings or set `fileformat` incorrectly. It's not a problem specific to this plugin; it's a problem with the malformed files you're editing. Whether or not you wish to do it, the real solution is to normalize the files' line endings. It's out of scope for this plugin to handle arbitrary cases of degenerate input data.
