### ISSUE TITLE
Not folding properly after ALEFix

### ISSUE THREAD

**Issue by gjeusel** [tmhedberg/SimpylFold#111]
## Informations
**Neovim version**
```
NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.0.5
```
**Operating system**
```
MacOS 10.13.6
```

## What went wrong
Folds are not updated after running [ALEFix](https://github.com/w0rp/ale) command.

## Steps to reproduce

- step 1: example file
```python
class SomethingCool:  # <-- fold #1
    def __init__(self):  # <-- fold #2
        pass

    def somemethod(self):  # <-- fold #2
        print("All Good ?")
```

- step 2: modify it
```python
class SomethingCool:  # <-- fold #1
    def __init__(self):  # <-- fold #2


        pass  # is producing error (too many blank lines)

    def somemethod(self):  # <-- fold #2
        print("All Good ?")
```

- step3: run `:ALEFix` and save
```python
class SomethingCool:  # <-- fold #1
    def __init__(self):  # <-- fold #2

        pass

    def somemethod(self):  # Not Folded !
        print("All Good ?")
```

## Minimal vimrc:

```vim
call plug#begin($HOME . "/.config/nvim/plugged")
  Plug 'tmhedberg/SimpylFold'
  Plug 'Konfekt/FastFold'
  Plug 'w0rp/ale'
call plug#end()

let g:python3_host_prog = $HOME . "/miniconda3/envs/neovim/bin/python"
let g:ale_fixers = {'python': ['yapf']}
```

**Comment by tmhedberg** [comment]
Do the folds look correct after you manually update them with the `zx` command?

**Comment by gjeusel** [comment]
Yes it does !
I just would have expected it to work at save using :
``` vim
let g:fastfold_savehook = 1
```

**Comment by tmhedberg** [comment]
SimpylFold doesn't decide when folds should be updated. It just provides the fold expression that Vim evaluates to determine where folds should be inserted. If that expression isn't being evaluated at the right time, that's a problem somewhere other than in SimpylFold itself.

I don't know anything about FastFold, but based on its GitHub description ("Speed up Vim by updating folds only when called-for."), claiming to reduce how often the fold expression is re-evaluated, I'd be inclined to suspect that it's malfunctioning somehow.
