### ISSUE TITLE
Folds are invalid after running formatter with ale

### ISSUE THREAD

**Issue by nkakouros** [tmhedberg/SimpylFold#118]
I am using ale to run the `black` python formatter. The problem I am facing is that after back runs and the code is formatted with new lines being added and old one concatenated, the folds do not get updated but they stay the same as before the formatting took place.

I do not know if this is an issue of ale or SimpylFold, but I thought I asked here first.

Is there a way to re-calculate the folds?

**Comment by tmhedberg** [comment]
[`zx` recalculates folds.](https://vimhelp.org/fold.txt.html#zx)

**Comment by nkakouros** [comment]
Wow.. thanks for the tip!

**Comment by lyz-code** [comment]
@tmhedberg @nkakouros I have a similar problem, when saving with black, all folds are opened, and if I use `zx` all folds are closed.

Does it happen to you too?
