### ISSUE TITLE
Releases Support

### ISSUE THREAD

**Issue by ejiek** [tmhedberg/SimpylFold#119]
Last release was in 2012 while the latest commit - in 2017.

It seams you've abandoned releases because a lot of plugin managers use git anyway.
There is still a demand for releases in distro packaging world.
[Arch Linux](https://aur.archlinux.org/packages/vim-simpylfold/) is an example.

If it's not too much of a burden, please, continue supporting releases.
Thanks!

**Comment by tmhedberg** [comment]
Sure, I just tagged the latest commit as `v2.0`. I believe that's all that's needed for it to count as a release on GitHub. If you need something more than that, let me know.
