### ISSUE TITLE
More configuration

### ISSUE THREAD

**Issue by manmat** [tmhedberg/SimpylFold#121]
Hey,

Is there a way to configure the plugin to not fold the code by default when I open a file? Is there a command to unfold all folds in the current file?

**Comment by tmhedberg** [comment]
Vim has built-in options for this. It doesn't need plugin support.

`:set nofoldenable` will disable folding by default; you can put that in your .vimrc or in a filetype-specific script.

The `zR` command opens all folds in the current file (and likewise, `zM` closes them all).

```
:help 'foldenable'
:help zR
```

**Comment by danuker** [comment]
I added this to my `vimrc`:

```vim
set foldlevel=20 " Open folds 20 levels deep
```
