### ISSUE TITLE
SimpylFold with large modules makes basic operations slow

### ISSUE THREAD

**Issue by MrMino** [tmhedberg/SimpylFold#122]
First and foremost: thanks for lots of good work put in so far. This issue should in no way be read as me trying to bash on it. I'm just reporting what I found and profiled, so that it might be used in further improvements.

SF is making basic operations (like deleting a char with <kbd>x</kbd>) laggy.

I was editing [Python/CPython/Lib/pwd.py](https://github.com/python/cpython/blob/master/Lib/pdb.py) (large module with 1.7k LoC), when it occurred to me that it gets sluggishly slow to change single characters, undo, etc.

I've done a simple repro on this module: 
 - open the file
 - [start up the profiler](https://stackoverflow.com/a/12216578/2146491)
 - go to line 151
 - <kbd> $ </kbd>
 - <kbd>x</kbd> ~3 times
 - stop the profiler, quit via `noautocmd`
 
The top items for Vim profiler were - if I'm reading the profile log the right way:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   23   2.440472   0.000943  SimpylFold#FoldExpr()
    8   2.439529   1.721571  <SNR>70_cache()
10728   0.380622   0.295177  <SNR>70_multi_string()
10232   0.181536             <SNR>70_indent()
 9800   0.152330             <SNR>70_blanks_adj()
 6384   0.085445             <SNR>70_matchstrpos()
```

All of them belong to SF.

After uninstalling the plugin, while performing the steps outlined above, everything seems to go back to normal

**Comment by MrMino** [comment]
Here are two profiler logs from vim - one with, one without SimpylFold installed.

While it's not as drastic as the ones I've shown above, the one here still points to SF as the culprit.

[with_sf.log](https://github.com/tmhedberg/SimpylFold/files/5773745/with_sf.log)
[without_sf.log](https://github.com/tmhedberg/SimpylFold/files/5773747/without_sf.log)

**Comment by jessefogarty** [comment]
The author mentions people should look into FastFold. It's a project aimed at helping increase the performance of folding in Vim generally. The way by default code folding is handled leads to redundant reprocessing especially when you're in insert mode.

Try setting up FastFold and see if it helps your SF installation. Not sure if performance for large modules is on the devs is on the todo list.

Hope it helps you :) Best of luck!

**Comment by MrMino** [comment]
I finally got around to testing `FastFold`. It works brilliantly with SimpylFold. Thanks for the suggestion - I missed that part of the README.
