### ISSUE TITLE
Plugin ceases to work if a module is named after its parent directory

### ISSUE THREAD

**Issue by MrMino** [tmhedberg/SimpylFold#125]
E.g. when you try to `vim mylib/mylib.py`, the plugin does not work. No error messages are shown, nothing out of usual, it just has no effect.

Vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
```

Plugin version: 0459df8.

**Comment by tmhedberg** [comment]
Can't reproduce this at the latest version. Please reopen if you have a reproducible case you can share.
