### ISSUE TITLE
is it possible to have only 1 line separating folds ?

### ISSUE THREAD

**Issue by LuisBL** [tmhedberg/SimpylFold#132]
Could we configure to have only one line (or even zero) ?

![image](https://user-images.githubusercontent.com/694774/166116731-c5c0fb2d-99ef-4d5e-980f-17f2646c56c3.png)

**Comment by tmhedberg** [comment]
Add `let g:SimpylFold_fold_blank = 1` to your `.vimrc`.

This is documented in the README but doesn't seem to be mentioned in the help file. I'll add it there.

**Comment by tmhedberg** [comment]
Fixed the documentation issue in ff4c85197c5555715093c08a8d4f9d493c4d80cd.
