### ISSUE TITLE
the function/class names should have an higher contrast than the lines numbers

### ISSUE THREAD

**Issue by LuisBL** [tmhedberg/SimpylFold#133]
The function/class names should have an higher contrast than the lines numbers

## Could it be possible to replace this:

![Sélection_989](https://user-images.githubusercontent.com/694774/166117262-abaafa80-2254-4c6d-99c2-65c5197a3969.png)

### By this with more contrast on what is more important:

![Sélection_989_n](https://user-images.githubusercontent.com/694774/166117277-b22bc28a-d1ef-488c-967d-0d207f985e44.png)

**Comment by tmhedberg** [comment]
No, Vim applies the `Folded` highlight group to the entire line. It's not possible to highlight parts of the line differently.

FYI, highlighting behavior is built in to Vim and doesn't have anything to do with this plugin.

**Comment by LuisBL** [comment]
Ok,
Could you point me to where in the code we use this default builting vim highlighting in SimplyFold so I can try to make a specific one to achieve this ?

**Comment by tmhedberg** [comment]
It does not appear anywhere in the code for this plugin. Highlighting is an entirely separate concern from folding. Your color scheme defines how text is highlighted; SimpylFold doesn't know or care about it.

`:help Folded` will show you the documentation for the relevant highlight group. But, like I said in my previous comment, you simply can't do what you're trying to do in Vim, unless you're willing to patch Vim's source code. It's just not designed to work that way.
