### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by foxTr0t1178** [tmhedberg/SimpylFold#135]
cloning the git repository asks for the username and password for my Github account, I provide both and the error:

`remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.`
`remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.`
`fatal: Authentication failed for 'https://github.com/tmhedberg/SimplyFold.git/'`

So I made a personal access token, and typed that in place of my password, but it returned with:
`remote: Repository not found.`
`fatal: repository 'https:/github.com/tmhedberg/SimplyFold.git/' not found`

**Comment by tmhedberg** [comment]
You misspelled the name of the repository in the URL. It's `SimpylFold`, not `SimplyFold`.
