### ISSUE TITLE
Folding Code in Child Classes 

### ISSUE THREAD

**Issue by b-goldney** [tmhedberg/SimpylFold#136]
Thanks a lot for this plugin - great solution. This question could simply be user error or an edge case.  A common pattern when using AWS dev ops solutions (CDK) is using inheritance and defining a lot of functions and classes at the same indent level as the super keyword (see example below). When I fold any code at the same indent level as the super keyword then ALL the code is folded - this can sometimes be a few hundred lines of code. 

Is there a way to solve this? Ideally, I could fold only `MyStack`.

```
class MyStage(Stage):
    """Example stage."""

    def __init__(
        self,
        scope: Construct,
        id: str,
        MyStack: Stack,
        stack_id,
        env: Environment,
        environment_variables,
        **kwargs: Any
    ):
        super().__init__(scope, id, env=env, **kwargs)

        # Create stacks here - same indent level as super keyword. 
        # There could be a few hundred lines of code below this at the same indent level
        MyStack(
            self,
            id="MyStack",
            environment_variables=environment_variables,
        )
```

**Comment by tmhedberg** [comment]
I'm not familiar with AWS configuration, but your example is not defining a class, but rather appears to be instantiating a class. Assuming I'm interpreting that correctly, I don't see how we can reliably differentiate between this and any arbitrary function invocation. Imagine an ordinary function (not a class) called `MyStack`—how could we tell the difference between calling that function and creating an instance of a `MyStack` class?

I'm not interested in introducing any AWS-specific special casing here, but if there's a generic way to identify the specific syntactic cases which you'd like to be folded, we could consider adding an option for that.

**Comment by akila-advisory** [comment]
I probably didn't use the best example with a class being instantiated; however, the majority of use cases are where functions are being invoked.  That said, based off your comments, I don't think there's a reasonable use case for this.  Thanks for the clarity and following up.

**Comment by b-goldney** [comment]
I probably didn't use the best example with a class being instantiated; however, the majority of use cases are where functions are being invoked. That said, based off your comments, I don't think there's a reasonable use case for this. Thanks for the clarity and following up.
