### ISSUE TITLE
SimpylFold won't indent top level functions

### ISSUE THREAD

**Issue by allopislozano** [tmhedberg/SimpylFold#137]
Example code:
```
def a(x):
    my_code_here....
    

def b(y):
    my_other_code_here...
```

How can I get SimpylFold to define folds for a and b functions located at the top level of the python file? 

Thanks

**Comment by tmhedberg** [comment]
It does.

Do you have `'foldminlines'` set to a value larger than the length of the functions?

**Comment by allopislozano** [comment]
I have it set to 1

**Comment by allopislozano** [comment]
@tmhedberg  I have fixed it. My vimrc files were a bit messy so at some point this fold level was being set incorrectly. Thanks

**Comment by allopislozano** [comment]
Oh I think I found the issue.  I have a tabstop of 2 . My python files have 2 spaces instead of a tab and in that case SimpylFold won't calculate the spaces properly. Looks like it needs a minimum of 4 spaces to detect it as an indentation level. Can this be fixed?
```
def f1(abcd):
 pass #no fold
def f2(abcd):
  pass #no fold
def f3(abcd):
   pass #no fold
def f4(abcd):
    pass #fold!! 
```

**Comment by allopislozano** [comment]
looks like setting softtabstop to 2 as well fixes the issue
