### ISSUE TITLE
class or def without spaces in between

### ISSUE THREAD

**Issue by nobuosato** [tmhedberg/SimpylFold#21]
If I write 2 classes with out space in between, the folding of the first class absorbs 
the adjacent class or def. This happens for defs with sub defs. For instances

class test()
      def __init__()  
class test2()
       def __init__()

folds to 

class test().....

**Comment by Beagle** [comment]
@tmhedberg 

This issue appears to be resolved. Tested with the following code:

```
class test():
    def init(): pass

class test2():
    def init(): pass
```
