### ISSUE TITLE
conflict with ultisnips

### ISSUE THREAD

**Issue by kevin4fly** [tmhedberg/SimpylFold#29]
it is conflict with [ultisnips](https://github.com/SirVer/ultisnips)

when i am opening a python file, typing `class` and followed by `<tab>` key to trigger a python class completion, `SimpylFold` folds the code where i am typing.

**Comment by kevin4fly** [comment]
here is a walk around:
```vim
autocmd filetype python setlocal foldopen+=insert
```

though it is not that perfect, it works.

**Comment by mgedmin** [comment]
Have you filed an UltiSnips bug?  Because it sounds like a UltiSnips bug to me.

**Comment by nfnty** [comment]
This is an inherit problem of using vim and is solved by using [FastFold](https://github.com/Konfekt/FastFold).

**Comment by youz17** [comment]
> This is an inherit problem of using vim and is solved by using [FastFold](https://github.com/Konfekt/FastFold).

sorry, I can not understand you idea, could you say more detailed.
I meet this question also.
thank you.
