### ISSUE TITLE
Incompatibility with restore_view.vim

### ISSUE THREAD

**Issue by MisterVulcan** [tmhedberg/SimpylFold#32]
This is rather obvious, but using this plugin and restore_view.vim (which stores folding information) simultaneously results in some erratic behavior, like lines in a function being randomly excluded from the fold, parts of different functions being folded together, etc. Disabled restore_view.vim because I need this plugin more. I apologize that I don't have much more information on why this issue exists.

**Comment by tmhedberg** [comment]
I'm not familiar with that plugin, but it looks like it's basically just some autocommands that call `:mkview` and `:loadview`. Does the same behavior occur if you use those commands manually? Can you provide an example file which exhibits this behavior?

**Comment by nfnty** [comment]
Unfortunately `mkview` and `loadview` don't work very well, as they save/restore way too much state, when you're probably only interested in something more akin to`winsaveview()` and `winrestview()`. I've come up with a solution that I may make a plugin out of, but it only currently works for neovim natively, but could probably use Python to work around that limitation.

**Comment by Konfekt** [comment]
There is also https://github.com/kopischke/vim-stay which does restore_view.vim does, but perhaps more properly.
