### ISSUE TITLE
foldmethod=syntax prevents folding

### ISSUE THREAD

**Issue by hovissimo** [tmhedberg/SimpylFold#33]
I almost gave up on trying to make SimpylFold work.  I've been trying to get Python folding for a long time, and my .vimrc still set fdm='syntax' for python files.  There's no indication that this is incorrect for SimpylFold, and it's easy to assume that syntax folding is appropriate.

Please consider making a note in the README that setting fdm='syntax' will prevent SimpylFold from working.

**Comment by Beagle** [comment]
@tmhedberg Based on your commit on May 24, I think this issue can be closed.

**Comment by tmhedberg** [comment]
You're right, thanks.
