### ISSUE TITLE
need to key combination to fold / unfold

### ISSUE THREAD

**Issue by mayuroks** [tmhedberg/SimpylFold#35]
The plugin is really useful and works out of the box. The current combination I use to fold unfold is 'z a'. I want to change it to Enter key. How should I do it ? Just fyi NERDTree allows to show / hide a directory  by pressing the Enter key. Convenience reasons !!

**Comment by tmhedberg** [comment]
I don't think it's really a SimpylFold-specific question, but you probably want to know about mapping commands. See `:help key-mapping` in Vim for the full documentation on this.

For your particular case, you can probably use something like the following to get what you want:

    :nnoremap <Enter> za
