### ISSUE TITLE
Module Docstring not folded

### ISSUE THREAD

**Issue by Hotschke** [tmhedberg/SimpylFold#43]
I'd like to fold the module docstring in my python file.
Consider following content:

```
#!/usr/bin/env python2.7
"""
This module does ... (module docstring)

Author: ...
"""

# source code comes here
import ...
```

At the moment this docstring is not folded by SimpylFold. Is it possible to add this?
Possibly related is https://github.com/tmhedberg/SimpylFold/pull/18

**Comment by tmhedberg** [comment]
Yes, it's possible to add it. Patches welcome. :)

**Comment by Hotschke** [comment]
I tried pull request #18 and this actually provides folding of the module docstring.

I have noticed that the pull request was first merged then reverted because of multi-line strings defined with `"""` which would be a different kind of folds.

Is there any middle ground to apply #18. I could see a sensible way to require only leading whitespace before `"""` to identify docstring related `"""`. If someone else has a good counter example, it would make it more trickier.

**Comment by tmhedberg** [comment]
I'm not really opposed to re-applying #18 as long as the bug that it introduced is fixed, but I'd personally prefer to only fold actual docstrings (*not* multi-line strings occurring in arbitrary locations, as #18 does). This means that, in addition to the existing behavior, where docstrings following a `class` or `def` line are folded, we would also fold docstrings starting on either the first line of the file, or following a shebang line, like in your example.

In either case, I'm not likely to work on it myself in the near future, but I'd be happy to review another pull request.

**Comment by Hotschke** [comment]
I have encountered one issue regarding my proposal distinguishing docstring `"""` from multi-line strings whether only leading whitespace exist: There is the possibility that  `u"""` or `r"""` is the beginning of the docstring. Probably these cases could be explicitly added.
