### ISSUE TITLE
Misfold with comments before class methods

### ISSUE THREAD

**Issue by iago-lito** [tmhedberg/SimpylFold#44]
Here is a misfolded snippet (the method gets folded with the docstring). Is there a workaround yet? Or is this just not PEP8-compliant?

    class Class(object):
        """ docstring
        """

        # comment
        def method():
            pass

**Comment by squfrans** [comment]
i cannot reproduce this. flake8 also shows no warnings.

```
class Class(object):
+---  2 lines: """ docstring

    # comment
+---  2 lines: def method():
```

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  8 2016 13:38:49)
MacOS X (unix) version
Included patches: 1-1707
```

**Comment by tmhedberg** [comment]
Agreed, can't reproduce on Vim 7.4.1572.

Please reopen the issue if you are able to reproduce reliably.

**Comment by iago-lito** [comment]
I'm sorry to confirm :(

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 28 2015 22:53:35)
    Included patches: 1-803

this is Debian 8 with gnome shell..

    $ uname -a
    Linux etak 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

Here is my tiny file as I successively type `za`, no matter where my cursor is in the class:

![misfold](https://cloud.githubusercontent.com/assets/10091387/14555121/f8e2ddb6-02f0-11e6-8809-18bdf55cd46f.gif)


Any idea what may be going wrong?

**Comment by squfrans** [comment]
`803` is almost a year old.  not ancient, but vim moves quite fast.
my guess would be changes/bugfixes in the fold code (or related) since then...

**Comment by iago-lito** [comment]
I'll recompile then tell you :)

**Comment by tmhedberg** [comment]
Also, what's the value of your `foldminlines` option? If it's larger than the length of the docstring (which is short in your examples), it could lead to this behavior, which would be technically correct, but maybe confusing.

**Comment by iago-lito** [comment]
My `foldminlines` is set to `1`. Making the docstring longer yields the same result :(

![misfold](https://cloud.githubusercontent.com/assets/10091387/14597709/d553ac62-054e-11e6-8444-fc81f7eedb3e.gif)

**Comment by tmhedberg** [comment]
Have you tried it with a newer version of Vim yet?

Another possibility could be interference between plugins. You could try disabling your other plugins temporarily to see if the folding works correctly when only this plugin is enabled.

**Comment by iago-lito** [comment]
I have tried disabling all pathogen plugins except SimpylFold with no success.

I have tried ignoring my `.vimrc` with `vim -u NONE` but it does not even load SimpylFold then. Is there an easy way I can get vim working with only pathogen + SimpylFold on?

I have not tried recompiling vim yet because it would be a mess at work. I'll tell you when I do :)

**Comment by iago-lito** [comment]
Hey, this is a new Vim with a clean `.vim` folder and fresh plugins:

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 27 2016 14:32:10)
    Included patches: 1-2265

.. and the problem no longer occurs. Cheers :)
