### ISSUE TITLE
My functions are pre-folded when vim starts up

### ISSUE THREAD

**Issue by techgnosis** [tmhedberg/SimpylFold#47]
Everything is already folded up as soon as Vim starts. I don't see any way to change this behavior :(

**Comment by tmhedberg** [comment]
That's due to your Vim configuration, not the plugin. Try setting an option like `foldlevelstart` to control the default fold level, or turn off `foldenable` if you want it disabled entirely.

**Comment by techgnosis** [comment]
set foldlevelstart=1 worked great! Thanks so much for the speedy assistance!

**Comment by tmhedberg** [comment]
Happy to help!

**Comment by richin13** [comment]
Hello, setting option `foldlevelstart` does not seem to work any more. I'm on NeoVIM 0.3.0.

Any ideas? 😞

**Comment by michael-angelozzi** [comment]
`set foldlevel=1`
Worked for me in Neovim
