### ISSUE TITLE
Python docstring folding

### ISSUE THREAD

**Issue by asvc** [tmhedberg/SimpylFold#53]
Currently with `let g:SimpylFold_docstring_preview = 1` python docstrings are displayed folded. 

Example:
<img width="432" alt="screen shot 2016-03-02 at 23 41 19" src="https://cloud.githubusercontent.com/assets/300146/13465444/b420dbfc-e0d0-11e5-878e-9dc247616ba2.png">
Is it possible to leave doctring visible? Thanks.

**Comment by tmhedberg** [comment]
Yes, `let g:SimpylFold_fold_docstring = 0` should prevent docstring folding.

**Comment by asvc** [comment]
Tried this, doesn't help. Testing with the following code:
```python
import platform


def sys_type():
    """
    Returns system type
    """
    return platform.system()

def sys_version():
    """
    Returns system version
    """
    return platform.version()
```

Opening the file:
<img width="318" alt="screen shot 2016-03-03 at 21 37 20" src="https://cloud.githubusercontent.com/assets/300146/13495892/260e6402-e188-11e5-8d56-0c849deee7b9.png">

<kbd>leader</kbd>+<kbd>f2</kbd>:
<img width="268" alt="screen shot 2016-03-03 at 21 39 29" src="https://cloud.githubusercontent.com/assets/300146/13495944/6fc777c8-e188-11e5-8b60-b52c3a66040b.png">

As you can see, docstring lines are still folded. I have the following code in my `.vimrc`:
```vim
" Folding for *.py
autocmd BufWinEnter *.py setlocal foldexpr=SimpylFold(v:lnum) foldmethod=expr
autocmd BufWinLeave *.py setlocal foldexpr< foldmethod<
```

Full version of .vimrc: http://pastebin.com/JpkZvU8E

If I can help identifying a problem without vimscript knowledge – please let me know.

**Comment by tmhedberg** [comment]
I may have misunderstood your original question. Are you asking how to prevent the docstrings from being folded, or how to ensure that, when they are folded, the first line of the docstring remains visible on the fold?

**Comment by asvc** [comment]
I would say the 2nd option. Idea is to show the general code overview when user opens a file with bazillion of functions. Something like:
```python
import blah

# +-- 256 lines: def flip(coin): -----------------
""" Flips the :param: coin """

# +-- 16 lines: def stop_war(planet): ------------
""" Stops war on the :param: planet """

# +-- 512 lines: def something(): ----------------
""" Long description
     of complicated function
     which sounds like a hokku """
```
<kbd>#</kbd> is used just to avoid red highlights in Python code.

**Comment by tmhedberg** [comment]
I see, sorry for misunderstanding.

It's not displaying the docstring in the fold because you're not putting the first line of the docstring on the same line as the opening quotes. If you format your docstrings like this:

```python
"""This is a single-line docstring."""
```

or like this:

```python```
"""This is a multi-line docstring.
There's more than one line here.
"""
```

then they'll be displayed in the fold as long as you have `let g:SimpylFold_docstring_preview = 1` set.

Your use of a newline after the opening quotes is unconventional in Python; the common formatting conventions are standardized in [PEP 257](https://www.python.org/dev/peps/pep-0257/). This plugin generally assumes that you follow all of the widely used formatting conventions of the language. Handling idiosyncratic, non-standard formatting preferences correctly would require including a full Python parser in the plugin, which I'm not interested in doing.

This specific special case could be addressed by adding a few lines to the `SimpylFoldText` function. If you're interested in writing a patch that does this, I'd consider applying it.

**Comment by asvc** [comment]
Sure, I'll take a look tomorrow. Thanks.
