### ISSUE TITLE
Disable scree-left rulers

### ISSUE THREAD

**Issue by asvc** [tmhedberg/SimpylFold#54]
After the recent update of all plugins, this started to show in the screen-left area:
<img width="175" alt="screen shot 2016-03-05 at 00 55 06" src="https://cloud.githubusercontent.com/assets/300146/13533860/58f3fd24-e26d-11e5-9b81-15f521f31a35.png">
Screenshot is taken with all other plugins disabled. Pretty strange, as I haven't experienced this behavior yesterday... Any hint where it comes from? Thanks.

**Comment by tmhedberg** [comment]
That's the "fold column". See `:help 'foldcolumn'`. It's nothing specific to SimpylFold.

If you want to turn it off, `:set foldcolumn=0`. If you don't know where it's being turned on to begin with, try `:verbose set foldcolumn?`.

**Comment by asvc** [comment]
reminder to future self: _"Never update your .vimrc at night with options you don't fully understand"_. Thanks.
