### ISSUE TITLE
BundleInstall in vim report error, requiring github username and password

### ISSUE THREAD

**Issue by hicqu** [tmhedberg/SimpylFold#63]
I am using Vundle to manage my vim plugin. And after i add Plugin 'tmhedberg/SimpylFold' in my vundle_vimrc, I run BundleInstall command in vim. But there is error requiring github password and username. But I can exactly clone the repo in bash shell with git clone XXXXX command.
Could you help me?

**Comment by tmhedberg** [comment]
I don't know anything about Vundle. Perhaps you should ask for help from its maintainers.
