### ISSUE TITLE
Code examples in docstrings

### ISSUE THREAD

**Issue by anntzer** [tmhedberg/SimpylFold#65]
```
"""A module docstring

This is an example::

    def foo():
        ...

Right?

"""
```

Trying to fold this snippet results in the indented code example getting folded together with the line below ("Right?").

**Comment by tmhedberg** [comment]
Do you consider this to be a bug because you think the entire module docstring should be folded, or because you don't think the embedded code example should be folded? If the former, you should know that the plugin doesn't currently fold module docstrings (see #43).

**Comment by anntzer** [comment]
Sorry, I misdescribed the issue; edited the OP.

Additionally, this also affects function docstrings: it is impossible to have just the function docstring folded in the following:
```
def foo():
    """A module docstring

    This is an example::

        def foo():
            ...

    Right?

    """
    pass
```

**Comment by rflynn** [comment]
+1
