### ISSUE TITLE
Fold multiline import

### ISSUE THREAD

**Issue by petobens** [tmhedberg/SimpylFold#66]
Consider the following `py` file:

``` python
import pandas as pd
from foo import (baaaaaaaaaaaaaaaaaarz, baaaaaaaaaaaaaaz,
                 fooooooooooooooooo)
x = 'foo'
```

As it can be seen in the image  `fooooooooooooo)` does not get folded. I expect it to be folded:
![screen shot 2016-07-26 at 15 33 56](https://cloud.githubusercontent.com/assets/2583971/17150594/6b36ae74-5346-11e6-8c59-3c1f91de2d1f.png)

**Comment by j3r3miah** [comment]
@tmhedberg: This one is bugging me too and taking a quick look think I may see a typo [right here](https://github.com/tmhedberg/SimpylFold/blob/master/ftplugin/python/SimpylFold.vim#L175)...  Shouldn't that be `let b:in_import = 1`?

**Comment by tmhedberg** [comment]
Indeed it should be! Nice catch.

**Comment by j3r3miah** [comment]
Fixing that typo, though, @tmhedberg, causes something else to break badly.

```
### This code ###

import pandas as pd
import json

x = 'foo'

def function():
    pass

y = 'bar'

### Folded: ###

+--  4 lines: import pandas as pd                                                                                                                                                   

+--  4 lines: def function():

**Comment by tmhedberg** [comment]
9e7c1c9d9bd7404dc136c184fcc9680fc36a8ed9 fixes the typo. And yes, it's still broken.

Patches are welcome if you're interested in debugging this.

**Comment by j3r3miah** [comment]
I tried and gave up @tmhedberg. My vim-foo has been exceeded :-/

**Comment by petobens** [comment]
Great. Thanks!
