### ISSUE TITLE
Change of color of folded lines

### ISSUE THREAD

**Issue by antonioyanezunihd** [tmhedberg/SimpylFold#71]
I have just installed the plugin and it works great on the folding side.

However, folded pieces of code are substituted by a white foreground line, and as the rest of the editor black foreground, it is uncomfortable to read.

Is it possible to change the color in which the folded lines are appearing?

Thank you very much.

**Comment by tmhedberg** [comment]
This is controlled by your highlight settings in Vim. Check `:help :highlight` for the full documentation on how it works. You probably want to change the colors for the `Folded` highlight group.
