### ISSUE TITLE
Multiline string misfolds

### ISSUE THREAD

**Issue by heindsight** [tmhedberg/SimpylFold#82]
Misfolding occurs when the start of a multiline string is preceded by another string on the same line.

This happens because the `multi_string_start_regex` doesn't match if there are other quotes preceding the opening triple-quote.

For example:
```
def spam():
    return 'string', """
        Misfolds"""

def ham():
    pass
```
results in a single fold containing both `spam()` and `ham()`:
```
+ +--  6 lines: def spam():------------------------------
```
While:
```
def spam():
    return 'string', """
        Misfolds
    """

def ham():
    pass
```
results in a nested fold starting at the end of the multiline string:
```
- def spam():
|     return 'string', """
|         Misfolds
|++---  4 lines: """-------------------------
```

I spent a few hours today trying to craft a `multi_string_start` regex that will work correctly in all cases, but haven't succeeded so far.

**Comment by nfnty** [comment]
Thanks!

**Comment by heindsight** [comment]
Thanks, but the fix breaks docstring folding on vim versions < 7.4.1685 which don't have the `matchstrpos` function.

**Comment by nfnty** [comment]
Oh, didn't know that. Added a compatibility shim in a997e05ec4b1e122158d5357ca2d01fa506131dc. Thanks.
