### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by gbataille** [tmhedberg/SimpylFold#85]
I upgraded this morning and it seems to not work at all anymore

I tracked it down to commit 183e6e9... Use autoload
it works at 2dfeb35... Implement full caching 

not sure if something has changed in the setup or what.

I can see
```
foldexpr=SimpylFold(v:lnum)
foldmethod=expr
```

in my buffer which seems correct

my .vimrc is in github.com/gbataille/MyConfig/dotfiles

**Comment by nfnty** [comment]
No, that's not correct. Remove this from your `vimrc`:
```
autocmd BufWinEnter *.py setlocal foldexpr=SimpylFold(v:lnum) foldmethod=expr
autocmd BufWinLeave *.py setlocal foldexpr< foldmethod<
```

**Comment by gbataille** [comment]
cool, works. thanks! That was quick
did something change or did I copy something wrong from StackOverflow
sometime in the past ? :)

**Comment by nfnty** [comment]
`foldexpr` and `foldmethod` are handled by SimpylFold, so no idea why you added that in the first place.

**Comment by nfnty** [comment]
Why it didn't work is due to the logic and function names having been completely refactored over the previous month, increasing performance my several magnitudes and fixing all bugs.

**Comment by gbataille** [comment]
cool. thanks
