### ISSUE TITLE
Trailing Newlines at End of File are Hidden in Preceding Fold

### ISSUE THREAD

**Issue by beweedon** [tmhedberg/SimpylFold#87]
It is a common style to end files with a newline (appearing in an editor like Vim as a blank line at the end of the file). However, it's difficult to verify whether these new lines are actually in files when using SimpylFold, because they are hidden in the previous fold. For example, if you have the following code in Python:

![image](https://cloud.githubusercontent.com/assets/22893946/24426824/c9d30b3e-13bd-11e7-959b-15135aeefc76.png)

The file when fully folded will appear like this:

![image](https://cloud.githubusercontent.com/assets/22893946/24426808/b8859d88-13bd-11e7-82da-59e61def23ec.png)

Does it make sense to add an option to not fold in blank lines at the end of the file to avoid this problem?

**Comment by tmhedberg** [comment]
Vim inserts a newline at the end of most files by default (the `eol` option
controls this). Technically, if you have actually-visible blank lines at
the end of your file, then you have *multiple* consecutive newlines at the
end of the file; a single trailing newline would not produce a visible
blank line. This probably doesn't make much difference to your overall
request, though.

Personally, I don't see the use of extraneous blank lines and would
consider it a style error in my own code. Your style preferences may differ
from mine, of course, and that's fine, but I don't feel a compulsion to
complicate the plugin code with special cases like this one unless there's
a widespread prevailing opinion that this is something that people want,
and that the complexity cost of handling it differently outweighs the cost
of continuing to fold trailing blank lines into the previous definition.

**Comment by beweedon** [comment]
That makes perfect sense! Thanks for the response!

**Comment by nfnty** [comment]
This should be fixed as folding extraneous blank lines at EOF makes adding statements there much harder than it should be. Also it hides unwanted blank lines. This is easily fixable.

**Comment by nfnty** [comment]
Thanks!

**Comment by tmhedberg** [comment]
Thanks @nfnty. I didn't consider the problems you mentioned, but I agree in retrospect.
