### ISSUE TITLE
Syntax aware highlighting

### ISSUE THREAD

**Issue by charisz** [tmhedberg/SimpylFold#88]
I'm searching for some possibility the preserve syntax highlight or better 'coloration' of `class Name` or `function name` when the code is folded.
I would do also only for myself, but I'm not finding out where is highlighting of the folded code is defined.

**Comment by nfnty** [comment]
Not possible with how vim works. You can try changing the highlight groups `Folded` and `FoldColumn`. See `:help fold-colors` for more info.

**Comment by charisz** [comment]
Ok. I see. Could it be possible that the folding starts under the function/class name (in the next row)?

**Comment by nfnty** [comment]
Not likely that we'll support that anytime soon; related to #84.

**Comment by charisz** [comment]
Ok. Thank you.
