### ISSUE TITLE
Without softtabstop set only first foldlevel is found

### ISSUE THREAD

**Issue by yggdr** [tmhedberg/SimpylFold#89]
With commit 3983aa494f77a7f3bee45e0bb2e74cd7cd2b7d08 indent calculation was changed to use softtabstop instead of tabstop. This broke folding beyond the first level in my case as I hadn't set that option (giving it the default of 0). I don't see this documented, and I don't think softtabstop can always be considered set. Maybe check whether it's 0 and fall back to tabstop?

**Comment by tmhedberg** [comment]
Thanks, I added a fallback to `'tabstop'`.

**Comment by nfnty** [comment]
I improved it by also taking `shiftwidth` into account and only calculating the spaces per indent once per cache.
