### ISSUE TITLE
Not folding Properly

### ISSUE THREAD

**Issue by rosaliel** [tmhedberg/SimpylFold#90]
I installed SimpylFold using Vundle. Imports and methods defined inside classes fold fine,  but when it comes to functions it either folds only the line of the function definition or folds nothing at all (both illustrated in the attached screenshot) .

![image](https://cloud.githubusercontent.com/assets/21218554/26731800/e609e866-47bd-11e7-9079-c4f118876b41.png)

**Comment by tmhedberg** [comment]
Is there any chance you could share a copy of the file exhibiting this behavior? Also, what is the output of the following command?

```VimL
:set tabstop? softtabstop? shiftwidth?
```

**Comment by rosaliel** [comment]
I looked at it again, and noticed that it folds correctly 8 spaces indentations (therefore it folded correctly methods defined inside classes) but not 4 spaces indentation.

I fixed it with `set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab`

Thanks!
