### ISSUE TITLE
SimpylFold incompatible with vim 8?

### ISSUE THREAD

**Issue by wsfreund** [tmhedberg/SimpylFold#91]
I'm having issues with simpylfold which is not working in servers using vim 8, only in those using vim 7, though I haven't made an in-depth test to check it. Is this a known issue?

**Comment by tmhedberg** [comment]
No, SimpylFold works with Vim 8. I use it regularly. There must be some
other incompatible configuration on your Vim 8 systems.

**Comment by wsfreund** [comment]
Thanks for your reply, it seems that this line was the issue `autocmd BufWinEnter *.py setlocal foldexpr=SimpylFold(v:lnum) foldmethod=expr`.
