### ISSUE TITLE
[Feature request] Quick fold/unfold docstring in python

### ISSUE THREAD

**Issue by tuyenpm9** [tmhedberg/SimpylFold#93]
Hummm.. don't think that will be a feature request, but if I want to implement this feature, how it would be and what part of code I should look into, I'm totally new to vimL.  
```
def stdev(arr):
    """
    Compute the standard deviation.
    """
```  
I'd like to quick (un)fold all """ and """ after definition of function or class but keep unfold other things.

**Comment by tmhedberg** [comment]
Thanks for the suggestion, but I don't really feel that this kind of feature belongs in this plugin. It is supposed to be simple, with relatively few frills. Everyone has a personal pet feature that they'd like to see added, but if we said "yes" to all of them, then the plugin would no longer be simple and lightweight.

What you are suggesting could be implemented in your own Vim configuration, separately from this plugin. I suggest you pursue that as an alternative. To get started, I would suggest reading `fold.txt` in Vim's help files.

**Comment by shaypal5** [comment]
I gotta say that when I downloaded this plugin I just assumed it's gonna fold long docstrings. I write long module and class docstrings, but once I'm done with 'em I usually want them out of the way. For me, there's little use in folding the whole class definition, while I'm actually interested in folding docstrings and function definitions.

That's it, just voicing my support. I get that this is out of scope for this plugin.
