### ISSUE TITLE
[Question] Show Docstring of first line after """

### ISSUE THREAD

**Issue by tuyenpm9** [tmhedberg/SimpylFold#96]
With below function:
```
def stdev(arr):
    """
    Compute the standard deviation.
    second line of docstring
    """
```  
Current SimpyIFold shows `+--- 3 lines: """` but it'll be more logic if it shows `+--- 3 lines: Compute the standard deviation.`?  
I just ask, actually I'm okay with  `+--- 3 lines: """`, who care about docstring :)

**Comment by iago-lito** [comment]
I think [PEP8](https://www.python.org/dev/peps/pep-0008/) rather recommends docstrings like:

    def stdev(arr):
        """Compute the standard deviation.
        second line of docstring
        """

.. which should solve both problems, because everyone *does* cares about docstrings ;)
