### ISSUE TITLE
imports folding not working

### ISSUE THREAD

**Issue by cutelittleturtle** [tmhedberg/SimpylFold#98]
vim version 8.0.1366
installed spf13-vim
    - removed pymode
    - installed fastfold
    - installed foldtext (doesn't matter i tried with or without this plugin)

file type: python/python3

foldmethod=indent/marker/syntax

installed python plugin: yssource/python.vim, python_match.vim, pythoncomplete, neocomplete

**Comment by tmhedberg** [comment]
> foldmethod=indent/marker/syntax

Your report isn't very clear. Are you saying that you set `foldmethod` to each of these 3 values? SimpylFold only works with `foldmethod=expr`.

**Comment by cutelittleturtle** [comment]
Sorry about that. I meant setting `foldmethod` to each of the options.

**Comment by tmhedberg** [comment]
Each of the options that you listed, or each option including `expr`?

It's possible that one of the other plugins you have installed is interfering somehow. What is the output of `:verbose set foldmethod? foldexpr?`.

**Comment by JeffKwasha** [comment]
This is the only location that tells users how to enable this plugin:
set foldmethod=expr

The 'Usage' on the main page claims that it works without any configuration.  
Usage should mention that it requires foldmethod=expr.

**Comment by tmhedberg** [comment]
The plugin does work without any configuration. `foldmethod=expr` is [set automatically](https://github.com/tmhedberg/SimpylFold/blob/master/ftplugin/python/SimpylFold.vim#L8) by SimpylFold in Python buffers. If that's not happening for you, then you must have some other script that is interfering with that or overriding the `foldmethod` option with a different value.

**Comment by cutelittleturtle** [comment]
I see. I will try it on a clean install of vim first I guess. Thanks for the help.
