### ISSUE TITLE
Don't fold commented functions with previous functions

### ISSUE THREAD

**Issue by Noxbru** [tmhedberg/SimpylFold#99]
Hi, I have found that this plugin folds commented out functions with previous functions.

For example:

```python
def foo(bar):
    Pass

def bar(foo):
    Pass
```

is folded as two functions. But:

```python
def foo(bar):
    Pass

#def bar(foo):
    #Pass
```

is folded as just one function. Is there a way of having two folds?

Thanks in advance.

**Comment by tmhedberg** [comment]
I don't think that's really feasible. A comment is opaque text; I would oppose attempting to parse comments to see whether their contents look like code on philosophical grounds, plus it would complicate the plugin code and inevitably bring up all kinds of unanticipated edge cases.
